spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fanxl-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: fxl123
  session:
    store-type: REDIS
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  output:
    ansi:
      enabled: detect

server:
  context-path: /sport
  port: 80
  session:
    timeout: 3000

fanxl:
  security:
    social:
      qq:
        app-id: 101436428
        app-secret: dc32b667bce14e17ba4125d6fa7a991c
    browser:
      signUpUrl: /demo-signUp
#      loginPage: /demo-signIn.html
#    code:
#      image:
#        length: 6
#        width: 100
#        url: /user, /user/*

